version: '3.9'

networks:
  backend:
  frontend:

services:

  redis:
    image: redis
    ports:
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_REDIS}:6379"
    networks:
      - backend

  database:
    image: postgres
    volumes:
      - ./volumes/database:/var/lib/postgresql/data
    ports:
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_DATABASE}:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_NAME: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - backend

  server:
    build: ./server
    command: /code/scripts/startup.sh
    depends_on:
      database:
        condition: service_healthy
      mailhog:
        condition: service_started
      redis:
        condition: service_started
    networks:
      - backend
      - frontend
    ports:
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_SERVER}:8000"
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_SERVER_DEBUG}:51000"
    volumes:
      - ./server:/code
    environment:
      DEBUG_PTVSD: ${DEBUG_PTVSD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DJANGO_DATABASE_ENGINE: ${DJANGO_DATABASE_ENGINE}
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DJANGO_CORS_ALLOWED_ORIGINS: ${DJANGO_CORS_ALLOWED_ORIGINS}
      DJANGO_PHONENUMBER_DEFAULT_REGION: ${DJANGO_PHONENUMBER_DEFAULT_REGION}
      DJANGO_PHONENUMBER_DEFAULT_FORMAT: ${DJANGO_PHONENUMBER_DEFAULT_FORMAT}
      DJANGO_EMAIL_HOST: ${DJANGO_EMAIL_HOST}
      DJANGO_EMAIL_PORT: ${DJANGO_EMAIL_PORT}
      DJANGO_EMAIL_USE_TLS: ${DJANGO_EMAIL_USE_TLS}
      DJANGO_EMAIL_HOST_USER: ${DJANGO_EMAIL_HOST_USER}
      DJANGO_EMAIL_HOST_PASSWORD: ${DJANGO_EMAIL_HOST_PASSWORD}
      DJANGO_EMAIL_SENDER: ${DJANGO_EMAIL_SENDER}
      DJANGO_JWT_PRIVATE_KEY: ${DJANGO_JWT_PRIVATE_KEY}
      DJANGO_JWT_PUBLIC_KEY: ${DJANGO_JWT_PUBLIC_KEY}
      DJANGO_ACTIVATION_URL: ${DJANGO_ACTIVATION_URL}
      DJANGO_ACCOUNT_ACTIVATION_DAYS: ${DJANGO_ACCOUNT_ACTIVATION_DAYS}
      DJANGO_PASSWORD_URL: ${DJANGO_PASSWORD_URL}
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1

  client-react:
    build: ./client-react
    command: npm start
    depends_on:
      server:
        condition: service_started
    networks:
      - frontend
    ports:
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_CLIENT_REACT}:3000"
    volumes:
      - ./client-react:/code
      - /code/node_modules
    environment:
      REACT_APP_GRAPHQL_HTTP_ENDPOINT: ${REACT_APP_GRAPHQL_HTTP_ENDPOINT}
      REACT_APP_GRAPHQL_WS_ENDPOINT: ${REACT_APP_GRAPHQL_WS_ENDPOINT}

  mailhog:
    image: mailhog/mailhog
    entrypoint: ["/bin/sh", "-c", "MailHog &>/dev/null"]
    networks:
      - frontend
    ports:
      - "${DOCKER_PORTMAP_IP}:${DOCKER_PORTMAP_PORT_MAILHOG}:8025"
    logging:
      driver: none

